name: Generate Snake

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Generate GitHub Contribution Snake (Dark Mode)
        uses: Platane/snk@v3
        with:
          github_user_name: saidebinsabid
          outputs: |
            dist/github-contribution-grid-snake.svg
          color_snake: '#00FF00'
          color_dots: '#39FF14,#32CD32,#228B22,#006400,#003300'

      - name: Push to output branch
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
